services:
  pipeline:
    build: .
    container_name: mspr_nantes_pipeline
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./docs:/app/docs
    environment:
      - PYTHONPATH=/app
      - MPLCONFIGDIR=/tmp/matplotlib
      # Optionally set TEST_YEARS="2020 2022" here or when running
      # - TEST_YEARS=2022
    working_dir: /app
    # ENTRYPOINT is python, so we pass the script path as command
    command: src/run_pipeline.py
